### ISSUE TITLE
Updating code in docker or rebuild?

### ISSUE THREAD

**Issue by pjneder** [EricJMarti/inventory-hunter#27]
Is this or can this be setup so that docker can pull image updates without having to rebuild the container each time? I'm only a bit familiar with this so right now I just hit it with a big hammer by re-cloning the git repo and rebuilding the docker image. Not exactly the fastest or most efficient method. If you have ideas or want to update the how-to section with how-to-maintain it would be really appreciated.

Keep up the great work and thanks for helping to beat the scalpers! No way I'm paying +50%-stupid% markups.

Thanks!

**Comment by pjneder** [comment]
Thanks @Wood578Guy !  Dumb docker question , that I probably should know the answer to, but will ask here. Do you have to stop the docker before you rebuild it? If I understand containers at all, the image and the running container are separate entities. Is that correct?

Thanks!

**Comment by Wood578Guy** [comment]
Yea the containers are instances of your images.  You do not need to stop running/existing ones to build another.

I'll tell you how I do it, with the caveat that it's maybe not the best way, since i just learned/taught myself over the last few days.

First i pull down latest code with `git pull`, then rebuild with `docker build -t inventory-hunter .`.

Then I stop running containers with `docker stop <container name>` (list running containers with `docker ps` and `docker ps -a` will list running and stopped containers).

Then I remove the stopped containers with `docker container rm <container name>'

I always stop containers before creating new ones.  This is actually a good way to test new code - I keep my old containers around until I'm sure the new ones I built work.  If they don't, then i simply restart the old containers.

**Comment by pjneder** [comment]
Awesome, thanks for the feedback. I will leave this open for the moment so others can benefit from some docker and git basics. @EricJMarti can close if needed to keep issue count down.

**Comment by Ronux25** [comment]
Thank you for this. While I have used linux before as I own a Rasberry PI, I had no idea how Docker worked. Nice to know how to properly update the code.
