### ISSUE TITLE
[QUESTIONS] Config Refresh, Email Resending

### ISSUE THREAD

**Issue by TylerK999** [EricJMarti/inventory-hunter#3]
Thanks for making this! A few questions:

1. Once the config file has been loaded does the inventory-hunter need to be reloaded if a new URL is added? So far my testing says it does.

2. If I get an email about an in stock product what happens next? Will I get another email next check for the same product? 

3. If I get an email about an in stock product, then awhile later another product goes in stock will I get an email about the new one?

**Comment by EricJMarti** [comment]
1. Yes. If you edit the config file, you will need to stop the running Docker container and start a new one to pick up the changes (no need to rebuild the Docker image). This is because the config file is copied from your local filesystem into the container's filesystem, so any edits to the local copy won't automatically make their way into the running container.
2. I probably should have documented this behavior (my bad!). Right now, once a product becomes in stock, the script sends the "In Stock" email and stops checking that specific URL. This isn't ideal because it means you'll need to restart the container to start monitoring that product again. I'll fix this so that a restart won't be necessary in the future.
3. Yes, the script will continue monitoring other URLs after sending an "In Stock" email for one of the URLs in your config.

**Comment by EricJMarti** [comment]
I just committed a change that eliminates the need to restart after a product becomes in stock. Now, you will get an email every time a product goes from out of stock to in stock.
