### ISSUE TITLE
Dockerhub?

### ISSUE THREAD

**Issue by JoshuaMunoz** [EricJMarti/inventory-hunter#36]
Possible to put this in Dockerhub?

**Comment by EricJMarti** [comment]
Yes, I've been considering this.

**Comment by JoshuaMunoz** [comment]
That would be wonderful! I'll keep my fingers crossed for it!

**Comment by EricJMarti** [comment]
Still trying to get this project on Docker Hub. I created the project but I'm not able to get Docker Hub to build the project from GitHub. I will look into this more tomorrow.

**Comment by EricJMarti** [comment]
Got linux/amd64 building on Docker Hub: https://hub.docker.com/r/ericjmarti/inventory-hunter

Working on setting up multi-arch builds for ARM platforms.

**Comment by bruttal361** [comment]
Sorry if the question is stupid, but I'm using Docker Desktop for Windows 10 and I finished all the steps, but it shows no containers are running in Docker. I'm not sure what went wrong.

**Comment by EricJMarti** [comment]
@bruttal361 Which steps are you following? I haven't yet posted official instructions for Windows (this is on my backlog).

**Comment by bruttal361** [comment]
@EricJMarti I followed the same instructions as everyone else. So I guess this won't work on Windows yet?

**Comment by bruttal361** [comment]
@EricJMarti It works now, was missing the .yaml in the end. Thank you for the assistance and for writing this. Hopefully, I can finally get a card.

**Comment by EricJMarti** [comment]
Finally ready for prime time: https://hub.docker.com/r/ericjmarti/inventory-hunter

I updated [README.md](https://github.com/EricJMarti/inventory-hunter/blob/main/README.md) to instruct users to pull the latest image from Docker Hub instead of building the image themselves.

Of course, you are welcome to continue building your own image. Just keep in mind that the `docker_run.bash` script uses the Docker Hub image by default. This can be overridden with the `-i`argument:
```
pi@raspberrypi:~/inventory-hunter
$ ./docker_run.bash -i my-inventory-hunter ...
```
