### ISSUE TITLE
Curl version

### ISSUE THREAD

**Issue by bennmann** [EricJMarti/inventory-hunter#65]
To make this more universally auditable, it would be good to have a simple Curl bash script version.

Any thoughts on how to implement a cronjob like that?

**Comment by EricJMarti** [comment]
This project actually started its life with something similar to what you're referring to. This was the proof of concept:

```
$ until (curl -s $URL | grep -i "add to cart"); do sleep 1; done; echo $URL | mail -s "In Stock" $EMAIL
```

You start running into issues when you actually have to parse the html for specific tags (in other words, you get false alarms when the add to cart buttons for related products show up). Also, some sites are picky about the HTTP request header you send them (as an anti-scraping measure). Thus, I have since scaled up from that bash one-liner.
